### ISSUE TITLE
No Bonemeal functionality

### ISSUE THREAD

**Issue by DancerVlt69** [tinytransfem/Grass_Slabs#12]
If you use bonemeal on  Grass Slabs (and Stairs) it will have no effect. Is that an real issue or it is planed? I'm not sure.

**Comment by tinytransfem** [comment]
Thank you for all your feedback and issue reports, however this one I most likely will not be implementing as my modding is on a very beginner level and this would probably require me to reimplement the whole bonemeal and grass/flowers functionality, which I simply don't know how to do. Maybe some day :)

**Comment by DancerVlt69** [comment]
You're welcome. Nothing to thanks.
Also me too - verry beginner - roundabout 6 months ago I've start to learn coding in Java.

My tests with Bonemealable Blocks works fine on Blocks, and three of my four Slabs (for Stairs I haven't coded it), but on the upper sided Slabs it looks .... 
![2022-09-09_16 19 57](https://user-images.githubusercontent.com/49952690/189372188-37672c2f-ca44-4211-bb4a-938fe8ad4a59.png)

a lil bit  crazy. 

My idea was: creating my own ModDirtSlabBlock - Class 

`public class ModDirtSlabBlock extends SlabBlock implements BonemealableBlock { `

Why it will not work on one of my own slabs... I don't know. 

You've got a private message on CurseForge....

**Comment by DancerVlt69** [comment]
OK, Bonemeal on Dirt/Grass-Stairs is not the best idea. Unless the plant will be shrink a bit and will span an the right level ;) ;) ;)

![2022-09-09_17 53 37](https://user-images.githubusercontent.com/49952690/189397721-d30f3279-9432-4651-a7ba-984f5e8f2137.png)
