### ISSUE TITLE
Missing language: maybe for the next update: translation for de_DE

### ISSUE THREAD

**Issue by DancerVlt69** [tinytransfem/Grass_Slabs#6]
{
  "block.grassslabs.grass_stairs": "Grastreppe",
  "block.grassslabs.grass_slab": "Grasstufe",
  "block.grassslabs.grass_carpet": "Grasteppich",
  "block.grassslabs.dirt_stairs": "Erdtreppe",
  "block.grassslabs.dirt_slab": "Erdstufe",
  "block.grassslabs.dirt_carpet": "Erdteppich",
  "block.grassslabs.mycelium_stairs": "Myzeltreppe",
  "block.grassslabs.mycelium_slab": "Myzelstufe",
  "block.grassslabs.mycelium_carpet": "Myzelteppich",
  "block.grassslabs.dirt_path_stairs": "Trampelpfadtreppe",
  "block.grassslabs.dirt_path_slab": "Trampelpfadstufe",
  "block.grassslabs.dirt_path_carpet": "Trampelpfadteppich"
}

For "Erdtreppe / -stufe / -teppich" you can also use "Treppe / Stufe / Teppich aus Erde" . It's a bit longer but it sounds better in German.

**Comment by tinytransfem** [comment]
Thank you very much for this, your translation has been added and will be part of the next update for this mod!
