### ISSUE TITLE
Uh... How does this happen...

### ISSUE THREAD

**Issue by DogeKingChris** [tinytransfem/Grass_Slabs#7]
You guys are aware that grass paths are unobtainable even with silk touch on a shovel, right? you can only right click dirt to get the paths, you can't mine them. This needs to be fixed asap... the mod's kinda useless in survival rn...

**Comment by DogeKingChris** [comment]
These people saying silk touch picks up dirt paths obviously didn't test this themselves. I'm trying right now as I type, and nothing. It's always been like this though, I don't even need to be doing it to know.

**Comment by EvvL** [comment]
I just ran into this the other day when I installed this. Would love to be able to right click on the dirt stair with a shovel and have it converted. Maybe some recipe to make a path block would be easier.

**Comment by tinytransfem** [comment]
This has been fixed in today's update, thank you for the feedback.
